# Generated by Django 5.2.3 on 2025-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="song_images/"),
        ),
    ]
