# Generated by Django 5.2.3 on 2025-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="movie",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
