# Generated by Django 5.2.3 on 2025-06-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_song_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="reveal_snippet",
            field=models.FileField(blank=True, null=True, upload_to="song_snippets/"),
        ),
    ]
