# Generated by Django 5.2.3 on 2025-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_song_reveal_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
