# Generated by Django 5.2.3 on 2025-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_song_artist_alter_song_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
