# Generated by Django 5.2.3 on 2025-07-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_friendship"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_players", models.IntegerField(default=0)),
                ("average_time", models.FloatField(null=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.song"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
