# Generated by Django 5.2.3 on 2025-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_song_spotify_duplicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysong",
            name="language",
            field=models.CharField(
                choices=[
                    ("tamil", "Tamil"),
                    ("english", "English"),
                    ("hindi", "Hindi"),
                ],
                default="tamil",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="language",
            field=models.CharField(
                choices=[
                    ("tamil", "Tamil"),
                    ("english", "English"),
                    ("hindi", "Hindi"),
                ],
                default="tamil",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_average_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_last_played_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="english_total_songs_solved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_average_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_last_played_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hindi_total_songs_solved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_average_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_last_played_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tamil_total_songs_solved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userscore",
            name="language",
            field=models.CharField(
                choices=[
                    ("tamil", "Tamil"),
                    ("english", "English"),
                    ("hindi", "Hindi"),
                ],
                default="tamil",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="display_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="dailysong",
            unique_together={("date", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="song",
            unique_together={("display_date", "language")},
        ),
    ]
