# Generated by Django 5.2.3 on 2025-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_announcement_feedback_poll_polloption_pollvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="poll_type",
            field=models.CharField(
                choices=[("poll", "Poll"), ("question", "Question/Quiz")],
                default="poll",
                max_length=20,
            ),
        ),
    ]
